import { seedReferenceTime } from "@/lib/kyc/seed";
import type {
  PaymentMethod,
  RefundReason,
  RefundRequest,
  RiskLevel,
  TransactionStatus,
} from "./types";

/**
 * Fictional refund queue. Amounts sit either side of the high-value threshold
 * on purpose, so the approval control is visible without configuring anything.
 */
interface RefundDefinition {
  id: string;
  customerName: string;
  customerId: string;
  /** Years the account has existed at seed time. */
  tenureMonths: number;
  merchant: string;
  transactionId: string;
  /** Hours before the seed reference point. */
  transactionHoursAgo: number;
  requestedHoursAgo: number;
  transactionStatus: TransactionStatus;
  paymentMethod: PaymentMethod;
  originalAmountCents: number;
  requestedAmountCents: number;
  reason: RefundReason;
  customerNote: string;
  riskLevel: RiskLevel;
  signals: string[];
}

const DEFINITIONS: RefundDefinition[] = [
  {
    id: "RFD-4101",
    customerName: "Priya Raghavan",
    customerId: "CUS-20514",
    tenureMonths: 41,
    merchant: "Meridian Grocers",
    transactionId: "TXN-884201",
    transactionHoursAgo: 74,
    requestedHoursAgo: 4,
    transactionStatus: "settled",
    paymentMethod: "visa_credit",
    originalAmountCents: 8_640,
    requestedAmountCents: 8_640,
    reason: "duplicate_charge",
    customerNote: "Charged twice at the till; the second charge is not on my receipt.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4102",
    customerName: "Tobias Lindqvist",
    customerId: "CUS-18877",
    tenureMonths: 7,
    merchant: "Halcyon Electronics",
    transactionId: "TXN-884377",
    transactionHoursAgo: 120,
    requestedHoursAgo: 9,
    transactionStatus: "settled",
    paymentMethod: "virtual_card",
    originalAmountCents: 129_900,
    requestedAmountCents: 129_900,
    reason: "item_not_received",
    customerNote: "Courier marked the parcel delivered but nothing arrived at the building.",
    riskLevel: "high",
    signals: [
      "Third refund request in 30 days",
      "Shipping address changed 2 days before order",
    ],
  },
  {
    id: "RFD-4103",
    customerName: "Amelia Duarte",
    customerId: "CUS-19240",
    tenureMonths: 63,
    merchant: "Northline Rail",
    transactionId: "TXN-884410",
    transactionHoursAgo: 52,
    requestedHoursAgo: 11,
    transactionStatus: "settled",
    paymentMethod: "apple_pay",
    originalAmountCents: 14_250,
    requestedAmountCents: 14_250,
    reason: "service_cancelled",
    customerNote: "Service cancelled by the operator; ticket was not usable.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4104",
    customerName: "Marcus Oyelaran",
    customerId: "CUS-21008",
    tenureMonths: 3,
    merchant: "Vertex Gaming",
    transactionId: "TXN-884502",
    transactionHoursAgo: 30,
    requestedHoursAgo: 14,
    transactionStatus: "disputed",
    paymentMethod: "mastercard_debit",
    originalAmountCents: 74_900,
    requestedAmountCents: 74_900,
    reason: "unauthorized_transaction",
    customerNote: "I did not make this purchase and my card was in my wallet.",
    riskLevel: "high",
    signals: [
      "Card-not-present transaction from a new device",
      "Account opened 3 months ago",
      "Chargeback already filed with the issuer",
    ],
  },
  {
    id: "RFD-4105",
    customerName: "Sofia Brenner",
    customerId: "CUS-17332",
    tenureMonths: 88,
    merchant: "Cobalt Fitness",
    transactionId: "TXN-884533",
    transactionHoursAgo: 200,
    requestedHoursAgo: 19,
    transactionStatus: "settled",
    paymentMethod: "ach_transfer",
    originalAmountCents: 4_900,
    requestedAmountCents: 4_900,
    reason: "billing_error",
    customerNote: "Membership was cancelled in March but the monthly fee was taken again.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4106",
    customerName: "Henrik Vasquez",
    customerId: "CUS-20991",
    tenureMonths: 15,
    merchant: "Atlas Furniture",
    transactionId: "TXN-884610",
    transactionHoursAgo: 400,
    requestedHoursAgo: 26,
    transactionStatus: "settled",
    paymentMethod: "visa_credit",
    originalAmountCents: 189_000,
    requestedAmountCents: 94_500,
    reason: "product_defective",
    customerNote: "One of the two chairs arrived damaged; asking for half the order back.",
    riskLevel: "medium",
    signals: ["Partial refund of a split order"],
  },
  {
    id: "RFD-4107",
    customerName: "Chiara Bellini",
    customerId: "CUS-16420",
    tenureMonths: 52,
    merchant: "Solaris Travel",
    transactionId: "TXN-884655",
    transactionHoursAgo: 96,
    requestedHoursAgo: 31,
    transactionStatus: "pending",
    paymentMethod: "visa_credit",
    originalAmountCents: 62_300,
    requestedAmountCents: 62_300,
    reason: "service_cancelled",
    customerNote: "Flight cancelled by the airline; rebooking was not offered.",
    riskLevel: "medium",
    signals: ["Original transaction has not settled yet"],
  },
  {
    id: "RFD-4108",
    customerName: "Daniel Achebe",
    customerId: "CUS-21174",
    tenureMonths: 2,
    merchant: "Lumen Digital",
    transactionId: "TXN-884702",
    transactionHoursAgo: 20,
    requestedHoursAgo: 6,
    transactionStatus: "settled",
    paymentMethod: "virtual_card",
    originalAmountCents: 49_500,
    requestedAmountCents: 49_500,
    reason: "unauthorized_transaction",
    customerNote: "Subscription charged after I closed the account.",
    riskLevel: "medium",
    signals: ["Account opened 2 months ago", "Velocity: 2 disputes this week"],
  },
  {
    id: "RFD-4109",
    customerName: "Yuki Tanabe",
    customerId: "CUS-15903",
    tenureMonths: 104,
    merchant: "Kettle & Crane",
    transactionId: "TXN-884744",
    transactionHoursAgo: 64,
    requestedHoursAgo: 38,
    transactionStatus: "settled",
    paymentMethod: "mastercard_debit",
    originalAmountCents: 12_780,
    requestedAmountCents: 12_780,
    reason: "item_not_received",
    customerNote: "Order was never dispatched and the merchant stopped replying.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4110",
    customerName: "Rosa Marchetti",
    customerId: "CUS-18055",
    tenureMonths: 34,
    merchant: "Cascade Home",
    transactionId: "TXN-884801",
    transactionHoursAgo: 150,
    requestedHoursAgo: 44,
    transactionStatus: "settled",
    paymentMethod: "ach_transfer",
    originalAmountCents: 240_000,
    requestedAmountCents: 240_000,
    reason: "product_defective",
    customerNote: "Appliance failed within a week; merchant agreed to a full refund.",
    riskLevel: "medium",
    signals: ["Merchant has confirmed the return in writing"],
  },
  {
    id: "RFD-4111",
    customerName: "Elias Novak",
    customerId: "CUS-19788",
    tenureMonths: 26,
    merchant: "Pinegrove Books",
    transactionId: "TXN-884820",
    transactionHoursAgo: 46,
    requestedHoursAgo: 50,
    transactionStatus: "settled",
    paymentMethod: "apple_pay",
    originalAmountCents: 3_450,
    requestedAmountCents: 3_450,
    reason: "duplicate_charge",
    customerNote: "The app retried my payment and both attempts went through.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4112",
    customerName: "Nadia Farouk",
    customerId: "CUS-20337",
    tenureMonths: 19,
    merchant: "Orbit Mobility",
    transactionId: "TXN-884899",
    transactionHoursAgo: 340,
    requestedHoursAgo: 58,
    transactionStatus: "settled",
    paymentMethod: "visa_credit",
    originalAmountCents: 51_200,
    requestedAmountCents: 51_200,
    reason: "billing_error",
    customerNote: "Charged the annual plan after switching to monthly.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4113",
    customerName: "Grace Whitfield",
    customerId: "CUS-16988",
    tenureMonths: 71,
    merchant: "Harbour Coffee",
    transactionId: "TXN-884921",
    transactionHoursAgo: 27,
    requestedHoursAgo: 64,
    transactionStatus: "settled",
    paymentMethod: "mastercard_debit",
    originalAmountCents: 1_850,
    requestedAmountCents: 1_850,
    reason: "duplicate_charge",
    customerNote: "Tapped twice by mistake at the counter.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4114",
    customerName: "Ibrahim Cetin",
    customerId: "CUS-21290",
    tenureMonths: 5,
    merchant: "Vantage Audio",
    transactionId: "TXN-885004",
    transactionHoursAgo: 88,
    requestedHoursAgo: 70,
    transactionStatus: "settled",
    paymentMethod: "virtual_card",
    originalAmountCents: 320_000,
    requestedAmountCents: 320_000,
    reason: "item_not_received",
    customerNote: "Tracking has not updated in eleven days.",
    riskLevel: "high",
    signals: [
      "Device fingerprint shared with a rejected KYC application",
      "High-value order on a young account",
    ],
  },
  {
    id: "RFD-4115",
    customerName: "Lena Bergstrom",
    customerId: "CUS-17601",
    tenureMonths: 58,
    merchant: "Fernway Clinic",
    transactionId: "TXN-885077",
    transactionHoursAgo: 220,
    requestedHoursAgo: 82,
    transactionStatus: "settled",
    paymentMethod: "ach_transfer",
    originalAmountCents: 43_500,
    requestedAmountCents: 43_500,
    reason: "service_cancelled",
    customerNote: "Appointment cancelled by the clinic with less than a day's notice.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4116",
    customerName: "Owen Mbeki",
    customerId: "CUS-18442",
    tenureMonths: 44,
    merchant: "Trailhead Outfitters",
    transactionId: "TXN-885120",
    transactionHoursAgo: 130,
    requestedHoursAgo: 96,
    transactionStatus: "settled",
    paymentMethod: "visa_credit",
    originalAmountCents: 27_600,
    requestedAmountCents: 13_800,
    reason: "product_defective",
    customerNote: "One boot in the pair had a split seam.",
    riskLevel: "low",
    signals: [],
  },
  {
    id: "RFD-4117",
    customerName: "Camille Rousseau",
    customerId: "CUS-19511",
    tenureMonths: 30,
    merchant: "Aurora Interiors",
    transactionId: "TXN-885188",
    transactionHoursAgo: 260,
    requestedHoursAgo: 110,
    transactionStatus: "settled",
    paymentMethod: "visa_credit",
    originalAmountCents: 88_000,
    requestedAmountCents: 88_000,
    reason: "item_not_received",
    customerNote: "Delivery window passed twice with no contact from the merchant.",
    riskLevel: "medium",
    signals: ["Merchant dispute rate above portfolio average"],
  },
  {
    id: "RFD-4118",
    customerName: "Victor Almeida",
    customerId: "CUS-20760",
    tenureMonths: 12,
    merchant: "Copperline Bar",
    transactionId: "TXN-885233",
    transactionHoursAgo: 310,
    requestedHoursAgo: 128,
    transactionStatus: "settled",
    paymentMethod: "mastercard_debit",
    originalAmountCents: 9_200,
    requestedAmountCents: 9_200,
    reason: "unauthorized_transaction",
    customerNote: "Card was used after I reported it lost.",
    riskLevel: "medium",
    signals: ["Card reported lost before the transaction"],
  },
];

function at(baseTime: number, hoursAgo: number): string {
  return new Date(baseTime - hoursAgo * 3_600_000).toISOString();
}

function accountOpened(baseTime: number, months: number): string {
  const opened = new Date(baseTime);
  opened.setUTCMonth(opened.getUTCMonth() - months);
  return opened.toISOString().slice(0, 10);
}

/** Every refund starts pending; decided history is scripted by the platform seed. */
export function createSeedRefunds(baseTime = seedReferenceTime()): RefundRequest[] {
  return DEFINITIONS.map((definition) => ({
    id: definition.id,
    customerName: definition.customerName,
    customerId: definition.customerId,
    customerSince: accountOpened(baseTime, definition.tenureMonths),
    merchant: definition.merchant,
    transactionId: definition.transactionId,
    transactionDate: at(baseTime, definition.transactionHoursAgo),
    transactionStatus: definition.transactionStatus,
    paymentMethod: definition.paymentMethod,
    originalAmountCents: definition.originalAmountCents,
    requestedAmountCents: definition.requestedAmountCents,
    reason: definition.reason,
    customerNote: definition.customerNote,
    requestedAt: at(baseTime, definition.requestedHoursAgo),
    riskLevel: definition.riskLevel,
    signals: definition.signals,
    status: "pending",
    reviewer: null,
    decidedAt: null,
    decisionReason: null,
  }));
}
